% Loading the data required for the training purpose.
data = load('sample_drone.mat');
trainingData = data.Drone_original;

% Randomly shuffling the training data before the training procedure.
rng(0);
shuffledIdx = randperm(height(trainingData));
trainingData = trainingData(shuffledIdx,:);
 
% Training options required for training data. The program runs on the CPU.
options = trainingOptions('sgdm', ...
      'Momentum', 0.9000, ...
      'ExecutionEnvironment', 'CPU',...
      'MiniBatchSize', 5, ...
      'InitialLearnRate', 1e-3, ...
      'MaxEpochs', 50, ...
      'VerboseFrequency', 50, ...
      'Verbose', 1);

 % Faster RCNN is trained using a set of parmeters
[detector,info] = trainFasterRCNNObjectDetector(trainingData, lgraph, options, ...
        'NegativeOverlapRange',[0 0.2], ...
        'PositiveOverlapRange',[0.6 1]);